### PR TITLE
Experimental PG patch

### PR DESCRIPTION
**Pull request by tedaford**
This PR will add PostGreSQL support to Faulty as a patch. Verified to work using the unit tests of my humble anonymous enterprise web app.

### CODE REVIEW

**Comment by justinhoward** [comment]
This would be a great addition!

**Comment by tedaford** [comment]
Seems to work, at least on the limited example of 1 enterprise-level web application backend.  Suggestions and comments are welcome.

**Comment by tedaford** [comment]
Sounds good! I will research more as I am able;

> methods that connect to database
In my case, I tested it on a ruby project that was connecting to one DB directly using the PG gem, and one using ActiveRecord. I wrapped ActiveRecord separately. 

>statements that need excluding
I don't think BEGIN counts, COMMIT and ROLLBACK would need to be excluded, otherwise (I'm not a super Postgres expert) I think that's it

>integration tests
I absolutely agree

>docs
Again, I absolutely agree, I kind of take the position that the "code describes the comments to the machine", vs the other way around, documentation is at least as important as the code itself.

**Comment by justinhoward** [comment]
It looks like you may have accidentally removed the mysql2 dependency in the Gemfile, which causes the mysql specs to be skipped. Your tests for PG are also not running on CI. You'll need to add pg to the Gemfile as well, and make sure the patch is `require`d in spec_helper.

You'll see that we have to conditionally test mysql2 depending on the ruby version (we specifically don't support the mysql2 patch on Ruby 2.3). I'm guessing that's not necessary here.

**Comment by tedaford** [comment]
(ah, crud, I did do that, I was having trouble at the time getting mysql to build while testing locally and didn't use a branch on my fork- as an aside, everything else seems to work fine in arm64-based linux)
Will fiddle with things later as I get time

**Comment by justinhoward** [comment]
@tedaford Did you mean to close this? If you're no longer interested in pursuing this, there's no pressure of course. I may continue this work in the future since I do think this would be a valuable addition. Either way, thanks for your work!

**Comment by tedaford** [comment]
I meant to try to make it a "draft" PR to keep it from banging on the unit tests, if it's no bother I'll leave it- working on a branch right now

**Pull request closed without merging**
